version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: github.com/uber/jaeger-client-go
    versions:
    - 2.25.0+incompatible
    - 2.26.0+incompatible
- package-ecosystem: npm
  directory: "/add-service-node"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 20
  versioning-strategy: increase
